# Generated by Django 5.2.8 on 2025-12-03 00:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateField(default=django.utils.timezone.now)),
                ('narrative', models.TextField()),
                ('instructor_approval', models.BooleanField(default=False)),
                ('student_approval', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_narrative', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'students'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_narrative', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
