# Generated by Django 5.2.8 on 2025-12-05 00:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateField(default=django.utils.timezone.now)),
                ('truck_num', models.IntegerField(verbose_name='Truck number')),
                ('acceleration', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('braking', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('steering', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('shifting', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('rturn_approach', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('rturn_turning', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('rturn_complete_turn', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('rturn_signal_use', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('lturn_approach', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('lturn_turning', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('lturn_complete_turn', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('lturn_signal_use', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('lane_control', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('smooth_braking', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('proper_stop', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('proper_mirror', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('enter_interstate', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('proper_lane_change', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('speed_following_distance', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('exit_interstate', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('railroad_approach', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('railroad_crossing', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('railroad_completion', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('pull_over_deceleration', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('pull_over_smooth', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('pull_over_re_entry', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('recognize_traffic_hazards', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('recognize_ohead_hazards', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('obey_laws', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('smith_system_defensive_driving', models.IntegerField(choices=[(2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1'), (5, 'Level 5'), (3, 'Level 3')])),
                ('btw_hours', models.FloatField()),
                ('student_approval', models.BooleanField(default=False)),
                ('instructor_approval', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_road_skills', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'students'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_road_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
