# Generated by Django 5.2.8 on 2025-12-04 01:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackingSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateField(default=django.utils.timezone.now)),
                ('btw_hours', models.FloatField()),
                ('alley_dock', models.IntegerField(choices=[(5, 'Level 5'), (3, 'Level 3'), (2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1')])),
                ('straight_line', models.IntegerField(choices=[(5, 'Level 5'), (3, 'Level 3'), (2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1')])),
                ('off_set_backing_right', models.IntegerField(choices=[(5, 'Level 5'), (3, 'Level 3'), (2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1')])),
                ('off_set_backing_left', models.IntegerField(choices=[(5, 'Level 5'), (3, 'Level 3'), (2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1')])),
                ('parallel_park', models.IntegerField(choices=[(5, 'Level 5'), (3, 'Level 3'), (2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1')])),
                ('coupling', models.IntegerField(choices=[(5, 'Level 5'), (3, 'Level 3'), (2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1')])),
                ('uncoupling', models.IntegerField(choices=[(5, 'Level 5'), (3, 'Level 3'), (2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1')])),
                ('pull_ups', models.IntegerField(choices=[(5, 'Level 5'), (3, 'Level 3'), (2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1')])),
                ('encroachments', models.IntegerField(choices=[(5, 'Level 5'), (3, 'Level 3'), (2, 'Level 2'), (4, 'Level 4'), (1, 'Level 1')])),
                ('instructor_approval', models.BooleanField(default=False)),
                ('student_approval', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_backing_skills', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'students'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_backing_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
