# Generated by Django 5.2.8 on 2025-12-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_roadskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadskills',
            name='acceleration',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='braking',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='enter_interstate',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='exit_interstate',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='lane_control',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='lturn_approach',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='lturn_complete_turn',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='lturn_signal_use',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='lturn_turning',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='obey_laws',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='proper_lane_change',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='proper_mirror',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='proper_stop',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='pull_over_deceleration',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='pull_over_re_entry',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='pull_over_smooth',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='railroad_approach',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='railroad_completion',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='railroad_crossing',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='recognize_ohead_hazards',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='recognize_traffic_hazards',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='rturn_approach',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='rturn_complete_turn',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='rturn_signal_use',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='rturn_turning',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='shifting',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='smith_system_defensive_driving',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='smooth_braking',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='speed_following_distance',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='steering',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
    ]
