# Generated by Django 5.2.8 on 2025-12-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_backingskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backingskills',
            name='alley_dock',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='coupling',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='encroachments',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='off_set_backing_left',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='off_set_backing_right',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='parallel_park',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='pull_ups',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='straight_line',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='uncoupling',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
    ]
