# Generated by Django 5.2.8 on 2025-12-05 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_pretripinsp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretripinsp',
            name='brake_tests',
            field=models.IntegerField(choices=[(1, 'Chapter 1'), (2, 'Chapter 2'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5')]),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='coupling_area',
            field=models.IntegerField(choices=[(1, 'Chapter 1'), (2, 'Chapter 2'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5')]),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='drives_and_5th_wheel',
            field=models.IntegerField(choices=[(1, 'Chapter 1'), (2, 'Chapter 2'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5')], verbose_name='Drives & Fifth Wheel'),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='engine_compartment',
            field=models.IntegerField(choices=[(1, 'Chapter 1'), (2, 'Chapter 2'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5')]),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='in_cab_and_lights',
            field=models.IntegerField(choices=[(1, 'Chapter 1'), (2, 'Chapter 2'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5')], verbose_name='In-Cab & Exterior Lights'),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='rear_of_trailer',
            field=models.IntegerField(choices=[(1, 'Chapter 1'), (2, 'Chapter 2'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5')]),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='trailer_sides',
            field=models.IntegerField(choices=[(1, 'Chapter 1'), (2, 'Chapter 2'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5')], verbose_name='Trailer Sides & Cross-members'),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='trailer_tandems',
            field=models.IntegerField(choices=[(1, 'Chapter 1'), (2, 'Chapter 2'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5')]),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='truck_side_rear',
            field=models.IntegerField(choices=[(1, 'Chapter 1'), (2, 'Chapter 2'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5')], verbose_name='Truck Side & Rear'),
        ),
        migrations.CreateModel(
            name='ELDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(choices=[(1, 'Chapter 1: Orientation'), (2, 'Chapter 2: Control Systems / Dashboard'), (3, 'Chapter 3'), (4, 'Chapter 4'), (5, 'Chapter 5'), (6, 'Chapter 6'), (7, 'Chapter 7'), (8, 'Chapter 8'), (9, 'Chapter 9'), (10, 'Chapter 10'), (11, 'Chapter 11'), (12, 'Chapter 12'), (13, 'Chapter 13'), (14, 'Chapter 14'), (15, 'Chapter 15'), (16, 'Chapter 16'), (17, 'Chapter 17'), (18, 'Chapter 18'), (19, 'Chapter 19'), (20, 'Chapter 20'), (21, 'Chapter 21'), (22, 'Chapter 22'), (23, 'Chapter 23'), (24, 'Chapter 24'), (25, 'Chapter 25'), (26, 'Chapter 26'), (27, 'Chapter 27'), (28, 'Chapter 26'), (29, 'Chapter 29'), (30, 'Chapter 30'), (31, 'Chapter 31'), (32, 'Chapter 32')], verbose_name='Select Chapter')),
                ('lesson_plan', models.TextField()),
                ('score', models.IntegerField()),
                ('student_approval', models.BooleanField(default=False)),
                ('instructor_approval', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_eldt_and_score_sheet', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'students'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_eldt_and_score_sheet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
