# Generated by Django 5.2.8 on 2025-12-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_pretripinsp_brake_tests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldt',
            name='chapter',
            field=models.IntegerField(choices=[(1, 'Chapter 1: Orientation'), (2, 'Chapter 2: Control Systems / Dashboard'), (3, 'Chapter 3: Pre and Post - Trip Inspections'), (4, 'Chapter 4: Basic Control'), (5, 'Chapter 5: Shifting / Operating Transmissions'), (6, 'Chapter 6: Backing and Docking'), (7, 'Chapter 7: Coupling and Uncoupling'), (8, 'Chapter 8: Visual Search'), (9, 'Chapter 9: Communication'), (10, 'Chapter 10: Distracted Driving'), (11, 'Chapter 11: Speed Management'), (12, 'Chapter 12: Space Management'), (13, 'Chapter 13: Night Operation'), (14, 'Chapter 14: Extreme Driving Conditions'), (15, 'Chapter 15: Hazard Perception'), (16, 'Chapter 16: Skid Control / Recovery, Jackknifing and Other Emergencies'), (17, 'Chapter 17: Railroad - Highway Grade Crossings'), (18, 'Chapter 18: Identification and Diagnosis of Malfunctions'), (19, 'Chapter 19: Roadside Inspections'), (20, 'Chapter 20: Maintenence'), (21, 'Chapter 21: Handling and Documenting Cargo'), (22, 'Chapter 22: Environmental Compliance Issues'), (23, 'Chapter 23: Hours of Service Requirements'), (24, 'Chapter 24: Fatigue and Wellness Awareness'), (25, 'Chapter 25: Post-Crash Procedures'), (26, 'Chapter 26: External Communications'), (27, 'Chapter 27: Whistleblower / Coercion'), (28, 'Chapter 28: Trip Planning'), (29, 'Chapter 29: Drugs / Alchohol'), (30, 'Chapter 30: Medical Requirements'), (31, 'Chapter 31: Human Trafficking'), (32, 'Chapter 32: CSA Traffic Laws, FMCSR, PUCO')], verbose_name='Select Chapter'),
        ),
    ]
