# Generated by Django 5.2.8 on 2025-12-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_backingskills_alley_dock_and_more'),
        ('ratings', '0003_alter_roadskills_acceleration_and_more'),
        ('ratings', '0004_alter_eldt_chapter'),
    ]

    operations = [
    ]
