# Generated by Django 5.2.8 on 2025-12-09 16:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_merge_20251208_1908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldt',
            name='chapter',
            field=models.IntegerField(choices=[(1, 'Chapter 1: Orientation'), (2, 'Chapter 2: Control Systems / Dashboard'), (3, 'Chapter 3: Pre and Post - Trip Inspections'), (4, 'Chapter 4: Basic Control'), (5, 'Chapter 5: Shifting / Operating Transmissions'), (6, 'Chapter 6: Backing and Docking'), (7, 'Chapter 7: Coupling and Uncoupling'), (8, 'Chapter 8: Visual Search'), (9, 'Chapter 9: Communication'), (10, 'Chapter 10: Distracted Driving'), (11, 'Chapter 11: Speed Management'), (12, 'Chapter 12: Space Management'), (13, 'Chapter 13: Night Operation'), (14, 'Chapter 14: Extreme Driving Conditions'), (15, 'Chapter 15: Hazard Perception'), (16, 'Chapter 16: Skid Control / Recovery, Jackknifing and Other Emergencies'), (17, 'Chapter 17: Railroad - Highway Grade Crossings'), (18, 'Chapter 18: Identification and Diagnosis of Malfunctions'), (19, 'Chapter 19: Roadside Inspections'), (20, 'Chapter 20: Maintenence'), (21, 'Chapter 21: Handling and Documenting Cargo'), (22, 'Chapter 22: Environmental Compliance Issues'), (23, 'Chapter 23: Hours of Service Requirements'), (24, 'Chapter 24: Fatigue and Wellness Awareness'), (25, 'Chapter 25: Post-Crash Procedures'), (26, 'Chapter 26: External Communications'), (27, 'Chapter 27: Whistleblower / Coercion'), (28, 'Chapter 28: Trip Planning'), (29, 'Chapter 29: Drugs / Alcohol'), (30, 'Chapter 30: Medical Requirements'), (31, 'Chapter 31: Human Trafficking'), (32, 'Chapter 32: CSA Traffic Laws, FMCSR, PUCO'), (33, 'Final Exam Review'), (34, 'Final Exam')], verbose_name='Select Chapter'),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='brake_tests',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='coupling_area',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='drives_and_5th_wheel',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], verbose_name='Drives & Fifth Wheel'),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='engine_compartment',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='in_cab_and_lights',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], verbose_name='In-Cab & Exterior Lights'),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='rear_of_trailer',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='trailer_sides',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], verbose_name='Trailer Sides & Cross-members'),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='trailer_tandems',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='truck_side_rear',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], verbose_name='Truck Side & Rear'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateField(default=django.utils.timezone.now)),
                ('time_in', models.TimeField(verbose_name='')),
                ('break_am_out', models.TimeField(verbose_name='')),
                ('break_am_in', models.TimeField(verbose_name='')),
                ('lunch_out', models.TimeField(verbose_name='')),
                ('lunch_in', models.TimeField(verbose_name='')),
                ('break_pm_out', models.TimeField(verbose_name='')),
                ('break_pm_in', models.TimeField(verbose_name='')),
                ('time_out', models.TimeField(verbose_name='')),
                ('instructor_approval', models.BooleanField(default=False)),
                ('student_approval', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'students'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
