# Generated by Django 5.2.8 on 2025-12-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_eldt_chapter_alter_pretripinsp_brake_tests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_num', models.IntegerField()),
                ('truck_type', models.IntegerField(choices=[(1, 'School Bus'), (2, 'Trailor'), (3, 'Straight'), (4, 'Tractor'), (5, 'Pulled Trailor')])),
                ('truck_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='break_am_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='break_am_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='break_pm_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='break_pm_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lunch_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lunch_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='alley_dock',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='coupling',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='encroachments',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='off_set_backing_left',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='off_set_backing_right',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='parallel_park',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='pull_ups',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='straight_line',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='backingskills',
            name='uncoupling',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='brake_tests',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='coupling_area',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='drives_and_5th_wheel',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0, verbose_name='Drives & Fifth Wheel'),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='engine_compartment',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='in_cab_and_lights',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0, verbose_name='In-Cab & Exterior Lights'),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='rear_of_trailer',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='trailer_sides',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0, verbose_name='Trailer Sides & Cross-members'),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='trailer_tandems',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='pretripinsp',
            name='truck_side_rear',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0, verbose_name='Truck Side & Rear'),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='acceleration',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='braking',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='enter_interstate',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='exit_interstate',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='lane_control',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='lturn_approach',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='lturn_complete_turn',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='lturn_signal_use',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='lturn_turning',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='obey_laws',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='proper_lane_change',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='proper_mirror',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='proper_stop',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='pull_over_deceleration',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='pull_over_re_entry',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='pull_over_smooth',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='railroad_approach',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='railroad_completion',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='railroad_crossing',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='recognize_ohead_hazards',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='recognize_traffic_hazards',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='rturn_approach',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='rturn_complete_turn',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='rturn_signal_use',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='rturn_turning',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='shifting',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='smith_system_defensive_driving',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='smooth_braking',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='speed_following_distance',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='steering',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
    ]
