# Generated by Django 5.2.8 on 2025-12-11 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_trucks_alter_attendance_break_am_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadskills',
            name='truck_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.trucks'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='truck_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='truck_num',
            field=models.CharField(),
        ),
    ]
