# Generated by Django 5.2.8 on 2025-12-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_alter_roadskills_truck_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadskills',
            name='truck_num',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
        migrations.DeleteModel(
            name='Trucks',
        ),
    ]
