# Generated by Django 5.2.8 on 2025-12-11 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_alter_roadskills_truck_num_delete_trucks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_num', models.CharField()),
                ('truck_type', models.IntegerField(choices=[(1, 'School Bus'), (2, 'Trailor'), (3, 'Straight'), (4, 'Tractor'), (5, 'Pulled Trailor')])),
                ('truck_description', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='roadskills',
            name='truck_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.trucks'),
        ),
    ]
