# Generated by Django 5.2.8 on 2025-12-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_trucks_alter_roadskills_truck_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucks',
            name='truck_type',
            field=models.CharField(choices=[('School Bus', 'School Bus'), ('Trailor', 'Trailor'), ('Straight', 'Straight'), ('Tractor', 'Tractor'), ('Pulled Trailor', 'Pulled Trailor')]),
        ),
    ]
