# Generated by Django 5.2.8 on 2025-12-12 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0013_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
