# Generated by Django 5.2.8 on 2025-12-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0015_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='semail',
        ),
        migrations.RemoveField(
            model_name='students',
            name='snumber',
        ),
    ]
