# Generated by Django 5.2.8 on 2025-12-15 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0016_remove_students_semail_remove_students_snumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretripinsp',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'students', 'students__active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='student_pre_trip_insp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.OneToOneField(limit_choices_to={'groups__name': 'students'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
