# Generated by Django 5.2.8 on 2025-12-16 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0018_instructors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='crn',
        ),
        migrations.AlterField(
            model_name='instructors',
            name='instructor_id',
            field=models.OneToOneField(limit_choices_to={'groups__name': 'instructors'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
